### ISSUE TITLE
Construction System

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14-content#51]
The general idea here is that we will use yml prototypes to define "steps" to the recipe. Construction and deconstruction will be handled by a component which loads in these values from the prototype.

A step will be something like
```
type: recipe
  recipetype: advancedwall //defines which entity we will use this with/for
  buildstep: 2 //defines which step we are defining
  forwardstep: weldertool //defines the tool/tools component types used for the forward step
  backwardstep: crowbartool //defines the same for the backwards step
  forwardtakes: cablecoil //defines a usable component type needed for a forward step
  backwardgives: metal //defines a usable component type that will be given though a backwards step
  sound: crowbar.ogg //defines sound to be played when using this step
```

And then the 1st step will cause it to be deconstructed, and the last step will tell us that it is finished and possibly define the output entity type

**Comment by imw-Oculus** [comment]
Sane and simple

**Comment by PJB3005** [comment]
After some discussion on Discord with @RemieRichards @TheOperand and @Acruid we've had some ideas.

* Step-by-step specific tools (with the 6 SS13 tools) is absolutely fine, but it should be VERY cleanly integrated into the game. Literally a tooltip showing you which tool to use next while building say a computer is what we need.
* A centralize crafting menu like TG is absolutely necessary to make it easy to construct stuff. You want to build *anything*, you know where to find it. No looking up on a help article (no, in game help articles are usually too painful) which arcane ritual you need to perform to start construction. Also no "use item to open menu" stuff, because it may not even be obvious *what* item you need. I want to be able to type in "computer" and clearly see an entry for a computer, telling me which parts and tools I need and that I need a circuit.

**Comment by RemieRichards** [comment]
This was also covered: recipes should also be simple, easy to implement in Yaml, ie: the recipe's output should be fixed (ie: there's no "Security Computer" recipe, it's just a "Generic Computer" recipe, and then that computer component handles being given programs, or a "Door" recipe which is finalised with an outer material, etc.), something easily model-able with a tree

for the "Construction Tooltip" I think it should be a ghost/phantom icon of the item required, that appears over the object on mouse hover.

**Comment by outbools** [comment]
You mean that recipes should be generic, and all the possible variations should be handled by something else?

**Comment by RemieRichards** [comment]
I'm saying they should be generic yes.

There's no "Reinforced Wall" recipe, there is only a "Wall" recipe, and when it's finished you get a "Wall" object (Entity+Wall Component or something) which can be finished with a material (hit it with plasteel? reinforced wall, hit it with bananium? bananium wall)

The output of a recipe should be fixed, and "variations" should be handled by the output object, not the recipe.

**Comment by captkirk88** [comment]
You could always use c# to define recipes and include behavior as well all in one go.
Would allow the server owner to have considerable control over the behavior of content.

Somethin like
```csharp
interface IRecipe{
RecipeType Type {get;}
// SourceType.Player, SourceType.Object, SourceType.Event
IRecipe interact(SourceType sourceType, Context ctx);
}
```
Just a quick example.  Since c# is sent over the wire anyways.
